### ISSUE TITLE
miasm2/jitter/vm_mngr errors on FREEBSD build

### ISSUE THREAD

**Issue by PavelKotov1** [cea-sec/miasm#794]
Hello again!
Well, before going for Ubuntu or Kali decided to try my luck on FreeBSD. 11.1
While running setup.py build, looks like most if not all errors are happening because of  
**miasm2/jitter/vm_mngr.h** header, 
for instance:
note: expanded from macro 'uint128_t'
**#define uint128_t  __uint128_t**   (does not like double underscore)
and then as a result: use of undeclared identifier '__uint128_t'
20 errors limit is exceeded and compilations stops: in setup.py ValueError is raised.

I  hope there is a simple solution to that problem since it seems that all the errors are of the same nature.
Any help will be greatly appreciated!

**Comment by serpilliere** [comment]
Hi!

We use uint128_t when we use gcc jitter.
It seems that not *all* gcc support this feature.

I am a bit stuck here. 
It should work on ubuntu, but the point is interesting:
We decided some time ago to use this in order to have the jitter support for some 128 bit operation, but it seems it's not generic enough.

We will think about it to see if we can simply fix this and aviod the 128 use.

Can you try on ubuntu during this time?
Thank you for the bug report!

**Comment by PavelKotov1** [comment]
>>Can you try on ubuntu during this time?
I shall certainly do that ASAP and report back the results.

**Comment by PavelKotov1** [comment]
On Ubuntu 18.4 everything looks good. 
Results: 435/439 pass.

**Comment by commial** [comment]
Actually, all the test should work. Can you please paste the end of
test_all, with the associated errors?

**Comment by commial** [comment]
Thanks you for these details. Actually, there are several points here:
* the first bug, `full.py -g -ss -d -p -m ppc32b ../samples/md5_ppc32b 0x1000087C`, has been introduced in a very recent PR, it should be fixed soon (#796)
* the 3 others are being investigated, but seems related to an elfesteem bug
* z3 detection controls the launch of z3 regression tests. If it has not been detected, corresponding tests will not be launched (hence, no error will come from z3)
* pyz3 installation might be tricky. You can ensure z3 is correctly installed by running `import z3; x = z3.BitVec(chr(0x41), 32)` in a python shell. If you're installing it from source, don't forget to use `python scripts/mk_make.py --python`

**Comment by serpilliere** [comment]
Hi!

Can you please test with the latest elfesteem/miasm?
We just fixed 2 bugs :smile:

**Comment by PavelKotov1** [comment]
Just an FYI:
With properly installed Z3:
Result: 458/463 pass
ERROR smt2.py
Traceback (most recent call last):
  File "smt2.py", line 39, in <module>
    s.add(e_z3 != smt2_z3)
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 882, in __ne__
    a, b = _coerce_exprs(self, other)
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 1029, in _coerce_exprs
    b = s.cast(b)
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 1319, in cast
    _z3_assert(is_expr(val), "True, False or Z3 Boolean expression expected. Received %s" % val)
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 91, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: True, False or Z3 Boolean expression expected. Received [If(And(Extract(7,
                0,
                Extract(15, 0, Extract(31, 0, a) + b)*c) <<
        (LShR(d, 5 & 8 - 1) | d << 8 - (5 & 8 - 1)) !=
        0,
        True),
    a + 100,
    22) ==
 If(And(e +
        (1 ^
         Extract(0, 0, Extract(7, 0, a)) ^
         Extract(1, 1, Extract(7, 0, a)) ^
         Extract(2, 2, Extract(7, 0, a)) ^
         Extract(3, 3, Extract(7, 0, a)) ^
         Extract(4, 4, Extract(7, 0, a)) ^
         Extract(5, 5, Extract(7, 0, a)) ^
         Extract(6, 6, Extract(7, 0, a)) ^
         Extract(7, 7, Extract(7, 0, a))) !=
        0,
        True),
    Concat(mem64[a*a + 7],
           Concat(mem64[a*a + 6],
                  Concat(mem64[a*a + 5],
                         Concat(mem64[a*a + 4],
                                Concat(mem64[a*a + 3],
                                       Concat(mem64[a*a + 2],
                                        Concat(mem64[a*a + 1],
                                        mem64[a*a]))))))),
    Concat(mem64[a + 7],
           Concat(mem64[a + 6],
                  Concat(mem64[a + 5],
                         Concat(mem64[a + 4],
                                Concat(mem64[a + 3],
                                       Concat(mem64[a + 2],
                                        Concat(mem64[a + 1],
                                        mem64[a]))))))))]

ERROR sandbox_elf_ppc32.py ../samples/md5_ppc32b --mimic-env --jitter python
Traceback (most recent call last):
  File "sandbox_elf_ppc32.py", line 22, in <module>
    sb = Sandbox_Linux_ppc32b(options.filename, options, globals())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 902, in __init__
    super(Sandbox_Linux_ppc32b, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 55, in __init__
    cls.__init__(self, custom_methods, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 279, in __init__
    name=self.fname, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/loader/elf.py", line 60, in vm_load_elf
    e = elf_init.ELF(fdata, **kargs)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 756, in __init__
    self.parse_content()
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 771, in parse_content
    self.sh = SHList(self, self.sex, self.size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 473, in __init__
    s.parse_content(sex, size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 308, in parse_content
    desc = c[12 + namesz:12 + namesz + descsz]
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/strpatchwork.py", line 25, in __getitem__
    s.extend(array("B", self.paddingbyte * (end - l)))
MemoryError

ERROR z3_ir.py
Traceback (most recent call last):
  File "z3_ir.py", line 102, in <module>
    [(0xdeadbeef, 2), (0xdeadbeef + 3, 0)])
  File "z3_ir.py", line 26, in check_interp
    l = interp.as_list()
AttributeError: QuantifierRef instance has no attribute 'as_list'

ERROR sandbox_elf_ppc32.py ../samples/md5_ppc32b --mimic-env --jitter llvm
Traceback (most recent call last):
  File "sandbox_elf_ppc32.py", line 22, in <module>
    sb = Sandbox_Linux_ppc32b(options.filename, options, globals())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 902, in __init__
    super(Sandbox_Linux_ppc32b, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 55, in __init__
    cls.__init__(self, custom_methods, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 279, in __init__
    name=self.fname, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/loader/elf.py", line 60, in vm_load_elf
    e = elf_init.ELF(fdata, **kargs)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 756, in __init__
    self.parse_content()
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 771, in parse_content
    self.sh = SHList(self, self.sex, self.size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 473, in __init__
    s.parse_content(sex, size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 308, in parse_content
    desc = c[12 + namesz:12 + namesz + descsz]
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/strpatchwork.py", line 25, in __getitem__
    s.extend(array("B", self.paddingbyte * (end - l)))
MemoryError

ERROR sandbox_elf_ppc32.py ../samples/md5_ppc32b --mimic-env --jitter gcc
Traceback (most recent call last):
  File "sandbox_elf_ppc32.py", line 22, in <module>
    sb = Sandbox_Linux_ppc32b(options.filename, options, globals())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 902, in __init__
    super(Sandbox_Linux_ppc32b, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 55, in __init__
    cls.__init__(self, custom_methods, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 279, in __init__
    name=self.fname, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/loader/elf.py", line 60, in vm_load_elf
    e = elf_init.ELF(fdata, **kargs)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 756, in __init__
    self.parse_content()
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 771, in parse_content
    self.sh = SHList(self, self.sex, self.size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 473, in __init__
    s.parse_content(sex, size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 308, in parse_content
    desc = c[12 + namesz:12 + namesz + descsz]
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/strpatchwork.py", line 25, in __getitem__
    s.extend(array("B", self.paddingbyte * (end - l)))
MemoryError

And that one:
ERROR sandbox_elf_ppc32.py ../samples/md5_ppc32b --mimic-env --jitter gcc
Traceback (most recent call last):
  File "sandbox_elf_ppc32.py", line 22, in <module>
    sb = Sandbox_Linux_ppc32b(options.filename, options, globals())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 902, in __init__
    super(Sandbox_Linux_ppc32b, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 55, in __init__
    cls.__init__(self, custom_methods, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 279, in __init__
    name=self.fname, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/loader/elf.py", line 60, in vm_load_elf
    e = elf_init.ELF(fdata, **kargs)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 756, in __init__
    self.parse_content()
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 771, in parse_content
    self.sh = SHList(self, self.sex, self.size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 473, in __init__
    s.parse_content(sex, size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 308, in parse_content
    desc = c[12 + namesz:12 + namesz + descsz]
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/strpatchwork.py", line 25, in __getitem__
    s.extend(array("B", self.paddingbyte * (end - l)))
MemoryError

**Comment by a-vincent** [comment]
Hi,

for some reason, and looking at the backtrace, it looks like you are using an "old" elfesteem, without the recent patch.

Regards,
 Aymeric

**Comment by PavelKotov1** [comment]
C'est domage ma the result is still the same:
Result: 458/463 pass
**ERROR smt2.py**
Traceback (most recent call last):
  File "smt2.py", line 39, in <module>
    s.add(e_z3 != smt2_z3)
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 882, in __ne__
    a, b = _coerce_exprs(self, other)
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 1029, in _coerce_exprs
    b = s.cast(b)
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 1319, in cast
    _z3_assert(is_expr(val), "True, False or Z3 Boolean expression expected. Received %s" % val)
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 91, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: True, False or Z3 Boolean expression expected. Received [If(And(Extract(7,
                0,
                Extract(15, 0, Extract(31, 0, a) + b)*c) <<
        (LShR(d, 5 & 8 - 1) | d << 8 - (5 & 8 - 1)) !=
        0,
        True),
    a + 100,
    22) ==
 If(And(e +
        (1 ^
         Extract(0, 0, Extract(7, 0, a)) ^
         Extract(1, 1, Extract(7, 0, a)) ^
         Extract(2, 2, Extract(7, 0, a)) ^
         Extract(3, 3, Extract(7, 0, a)) ^
         Extract(4, 4, Extract(7, 0, a)) ^
         Extract(5, 5, Extract(7, 0, a)) ^
         Extract(6, 6, Extract(7, 0, a)) ^
         Extract(7, 7, Extract(7, 0, a))) !=
        0,
        True),
    Concat(mem64[a*a + 7],
           Concat(mem64[a*a + 6],
                  Concat(mem64[a*a + 5],
                         Concat(mem64[a*a + 4],
                                Concat(mem64[a*a + 3],
                                       Concat(mem64[a*a + 2],
                                        Concat(mem64[a*a + 1],
                                        mem64[a*a]))))))),
    Concat(mem64[a + 7],
           Concat(mem64[a + 6],
                  Concat(mem64[a + 5],
                         Concat(mem64[a + 4],
                                Concat(mem64[a + 3],
                                       Concat(mem64[a + 2],
                                        Concat(mem64[a + 1],
                                        mem64[a]))))))))]

**ERROR sandbox_elf_ppc32.py** ../samples/md5_ppc32b --mimic-env --jitter python
Traceback (most recent call last):
  File "sandbox_elf_ppc32.py", line 22, in <module>
    sb = Sandbox_Linux_ppc32b(options.filename, options, globals())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 902, in __init__
    super(Sandbox_Linux_ppc32b, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 55, in __init__
    cls.__init__(self, custom_methods, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 279, in __init__
    name=self.fname, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/loader/elf.py", line 60, in vm_load_elf
    e = elf_init.ELF(fdata, **kargs)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 756, in __init__
    self.parse_content()
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 771, in parse_content
    self.sh = SHList(self, self.sex, self.size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 473, in __init__
    s.parse_content(sex, size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 308, in parse_content
    desc = c[12 + namesz:12 + namesz + descsz]
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/strpatchwork.py", line 25, in __getitem__
    s.extend(array("B", self.paddingbyte * (end - l)))
MemoryError

**ERROR z3_ir.py**
Traceback (most recent call last):
  File "z3_ir.py", line 102, in <module>
    [(0xdeadbeef, 2), (0xdeadbeef + 3, 0)])
  File "z3_ir.py", line 26, in check_interp
    l = interp.as_list()
AttributeError: QuantifierRef instance has no attribute 'as_list'

**ERROR sandbox_elf_ppc32.py** ../samples/md5_ppc32b --mimic-env --jitter llvm
Traceback (most recent call last):
  File "sandbox_elf_ppc32.py", line 22, in <module>
    sb = Sandbox_Linux_ppc32b(options.filename, options, globals())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 902, in __init__
    super(Sandbox_Linux_ppc32b, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 55, in __init__
    cls.__init__(self, custom_methods, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 279, in __init__
    name=self.fname, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/loader/elf.py", line 60, in vm_load_elf
    e = elf_init.ELF(fdata, **kargs)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 756, in __init__
    self.parse_content()
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 771, in parse_content
    self.sh = SHList(self, self.sex, self.size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 473, in __init__
    s.parse_content(sex, size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 308, in parse_content
    desc = c[12 + namesz:12 + namesz + descsz]
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/strpatchwork.py", line 25, in __getitem__
    s.extend(array("B", self.paddingbyte * (end - l)))
MemoryError

**ERROR sandbox_elf_ppc32.py** ../samples/md5_ppc32b --mimic-env --jitter gcc
Traceback (most recent call last):
  File "sandbox_elf_ppc32.py", line 22, in <module>
    sb = Sandbox_Linux_ppc32b(options.filename, options, globals())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 902, in __init__
    super(Sandbox_Linux_ppc32b, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 55, in __init__
    cls.__init__(self, custom_methods, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 279, in __init__
    name=self.fname, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/loader/elf.py", line 60, in vm_load_elf
    e = elf_init.ELF(fdata, **kargs)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 756, in __init__
    self.parse_content()
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 771, in parse_content
    self.sh = SHList(self, self.sex, self.size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 473, in __init__
    s.parse_content(sex, size)
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 308, in parse_content
    desc = c[12 + namesz:12 + namesz + descsz]
  File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/strpatchwork.py", line 25, in __getitem__
    s.extend(array("B", self.paddingbyte * (end - l)))
MemoryError

**Comment by serpilliere** [comment]
Juste a question:
What is your source of elfesteeem?
The source supported by miasm is https://github.com/serpilliere/elfesteem as the README says (https://github.com/cea-sec/miasm/blob/master/README.md)

In your backtrace, we can see the line:
```
desc = c[12 + namesz:12 + namesz + descsz]
```
And currently, the elfesteem (on the git) code is https://github.com/serpilliere/elfesteem/blob/master/elfesteem/elf_init.py#L314:
```
 desc = c[hsz + namesz:hsz + namesz + descsz]
```
It seems there is a mismatch here :confused:
Мне нравится водка!

**Comment by PavelKotov1** [comment]
c'e la question tre juste!
I am taking my elfesteem by clicking on the link on this page https://github.com/cea-sec/miasm
here:
->>•elfesteem from Elfesteem
it take me to here: https://github.com/serpilliere/elfesteem

Then I git clone https://github.com/serpilliere/elfesteem.git

So maybe the link above is somehow misleading?

I am going to try to use the one you give and report the results as soon as possible.
D'accord?

**Comment by serpilliere** [comment]
Ok . So have you got at line 314:
```python
desc = c[hsz + namesz:hsz + namesz + descsz]
```
and not 
```python
desc = c[12 + namesz:12 + namesz + descsz]
```

Because your trace is not showing this

**Comment by PavelKotov1** [comment]
Line 314:  desc = c[hsz + namesz:hsz + namesz + descsz]

So, go ahead and  change it to what is should be?

**Comment by serpilliere** [comment]
But, man, this line is from the official repo, from the official code.
And it seems from you DO NOT HAVE this line in the elfesteem version you are using. I can read this from your *own* logs you published here:
```
File "/home/plutos/.local/lib/python2.7/site-packages/elfesteem/elf_init.py", line 308, in parse_content
desc = c[12 + namesz:12 + namesz + descsz]
```
In the file of YOUR elfesteem from the `putos ` user, the lines are from the *non* patched version of elfesteem.

I cannot help you if you DO NOT update your elfesteem.
Please, do the update & re install elfesteem before relaunching the tests

**Comment by PavelKotov1** [comment]
I have updated elfesteem 3 times with the same result. I am getting it from the official github depository following instructions to the letter.
Could please you give me a direct link to the place from where you are getting yours and I would be happy to update, rebuild and reinstall it before relaunching the tests. Or just put your elfesteem archive somewhere from where I could get it.
Merci bien!

**Comment by serpilliere** [comment]
The link: https://github.com/serpilliere/elfesteem

You can check yourself the file.
Maybe you are doing a missuse of git update or you have installed the package elfesteem from pip which is not supported by miasm.

try resolving your issue using `git log` to see if you have the last commits and so on

**Comment by serpilliere** [comment]
No problem :smiley: 
Thank you for the bug report!
