### ISSUE TITLE
Integer to double casting and comparison error: LLVM ERROR: Program used external function 'fcom_c0' which could not be resolved!

### ISSUE THREAD

**Issue by mp-ssi** [cea-sec/miasm#840]
Dear Miasm developers,

I encountered an error in the jitter which is linked with double precision float comparison. 
I would be very grateful if you could explain what is the reason and how could this be fixed ?

Many thanks for your help.

# Miasm commit

Current Miasm commit is:

```
commit 1e994249defba6024c48796443a66889466b5326
Merge: c9be70e deb7ba7
Author: Camille Mougey <commial@gmail.com>
Date:   Thu Aug 30 16:31:55 2018 +0200

    Merge pull request #838 from serpilliere/remove_malware_sample
    
    Remove malware sample
```

# Observed error

The jitted architecture is x86 64 bits.

The jitter fails at the following block (more precisely, it seems the CVTSI2SD instruction is the source of the error).

This block is extracted from a string length comparison routine which uses a double (40.8) instead of an integer (41). The string length is taken from R14. 

In the block

* 5 is subtracted from the length of the string
* the substraction result is casted from int to double using `CVTSI2SD`
* the result of the conversion is compared to 40.8 using `COMISD`.

```
; Initial state:
; RAX = 0x0d
; RCX = 8
; RSI  = 1
; R14 = 0x0d
; R15 = 1
; eflags = all 0

loc_10001857
ADD             ESI, R15D
ADD             R14D, EAX
PXOR            XMM0, XMM0
LEA             ECX, DWORD PTR [R14 + 0xFFFFFFFFFFFFFFFB]
CVTSI2SD        XMM0, RCX
COMISD          XMM0, QWORD PTR [RIP + 0xC026]                        ; QWORD PTR [RIP + 0xC026] = 0x4044666666666666 (equals 40.8)
JAE             loc_10001880
```

# Tested jitters

## GCC

Compilation warning:

```
/tmp/tmpXubFfo.c: In function ‘block_entry’:
/tmp/tmpXubFfo.c:205:15: warning: implicit declaration of function ‘fpu_fcom_c31’ [-Wimplicit-function-declaration]
  var_08_00 = (fpu_fcom_c31(sint_to_fp_64(bignum_to_uint64(bignum_mask(bignum_rshift(mycpu->XMM0, 0), 
               ^
/tmp/tmpXubFfo.c:207:15: warning: implicit declaration of function ‘fpu_fcom_c21’ [-Wimplicit-function-declaration]
  var_08_02 = (fpu_fcom_c21(sint_to_fp_64(bignum_to_uint64(bignum_mask(bignum_rshift(mycpu->XMM0, 0), 
               ^
/tmp/tmpXubFfo.c:209:15: warning: implicit declaration of function ‘fpu_fcom_c01’ [-Wimplicit-function-declaration]
  var_08_04 = (fpu_fcom_c01(sint_to_fp_64(bignum_to_uint64(bignum_mask(bignum_rshift(mycpu->XMM0, 0), 
               ^
```

Python backtrace:

```
Traceback (most recent call last):
  File "sb_emul_function.py", line 54, in <module>
    sb.run(URL_GENERATION_ADDR)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 534, in run
    super(Sandbox_Win_x86_64, self).run(addr)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 126, in run
    self.jitter.continue_run()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 387, in continue_run
    return self.run_iterator.next()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 358, in runiter_once
    self.pc = self.run_at(self.pc)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 315, in run_at
    set(self.breakpoints_handler.callbacks.keys())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore.py", line 186, in run_at
    cur_block = self.disasm_and_jit_block(offset, cpu.vmmngr)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore.py", line 163, in disasm_and_jit_block
    self.add_block(cur_block)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore_gcc.py", line 63, in add_block
    self.load_code(block.loc_key, fname_out)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore_gcc.py", line 28, in load_code
    lib = ctypes.cdll.LoadLibrary(fname_so)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/miasm_cache/ba59309516e5a6c3b1c590f55aa63bd7.so: undefined symbol: fpu_fcom_c21
```

## LLVM

No backtrace. It only states:

```
LLVM ERROR: Program used external function 'fcom_c0' which could not be resolved!
```

## Python

Backtrace:

```
10001865 CVTSI2SD   XMM0, RCX

Traceback (most recent call last):
  File "sb_emul_function.py", line 54, in <module>
    sb.run(URL_GENERATION_ADDR)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 534, in run
    super(Sandbox_Win_x86_64, self).run(addr)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 126, in run
    self.jitter.continue_run()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 387, in continue_run
    return self.run_iterator.next()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 358, in runiter_once
    self.pc = self.run_at(self.pc)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 315, in run_at
    set(self.breakpoints_handler.callbacks.keys())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore.py", line 200, in run_at
    self.options["max_exec_per_call"])
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore_python.py", line 146, in exec_wrapper
    return fc_ptr(cpu)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore_python.py", line 108, in myfunc
    exec_engine.update_cpu_from_engine()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/emulatedsymbexec.py", line 92, in update_cpu_from_engine
    raise ValueError("A simplification is missing: %s" % value)
ValueError: A simplification is missing: {sint_to_fp(0x8) 0 64, 0x0 64 128}
```

**Comment by commial** [comment]
Hi,

First, thanks for your detailed issue!

#839 should fix the LLVM and GCC problems.

Regarding the Python one, the floating point unit is not implemented. Indeed, I didn't find a good way to manage Float in Python with proper rounding operation and precision mapped to IEEE 754.
I'm completely open to suggestion, If someone has one.

Please re-open the issue if the problem is not solve with #839 .

**Comment by mp-ssi** [comment]
Hi !

Thank you very much for your answer.

I've checked out the pull request and ran `setup.py build/install` again (following commit is now my currently installed miasm).

```
commit ecf6cac84d3330c923a6c65bb424e2911f9065a6
Author: Ajax <commial@gmail.com>
Date:   Thu Aug 30 14:42:08 2018 +0200

    Add support for more FP operations, expand fxam
```

Unfortunately I have the exact same problem :-(

I actually think the comparison using `COMISD` is the issue given the name of the operator throwing the exeption `fcom` (**com** as in **compare**) maybe ?

Cheers,

**Comment by commial** [comment]
Hi, thanks for the feedback.
Did you remove the Miasm cache after installing? (`/tmp/miasm_cache`)

**Comment by serpilliere** [comment]
In the case the bug is still there, may you share the sample you are running?
If yes, it may accelerate the debug process :smiley:

**Comment by mp-ssi** [comment]
Hi !

Clearing the cache solved the issue. It doesn't complain anymore.
Good trick to know !

Many thanks for your advice :)

Cheers,
